### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by Chris36839** [MedARC-AI/fMRI-reconstruction-NSD#37]
Hi, I'm encountering the following error while running "Train_MindEye.py" and am unable to resolve it. I hope someone can help me identify the issue and suggest possible solutions.
Firstly, I got the following error:
Traceback (most recent call last):
  File "/mnt/d/Files/Codes/fMRI-reconstruction-NSD/src/Train_MindEye.py", line 585, in <module>
    for train_i, (voxel, image, coco) in enumerate(train_dl):
  File "/root/miniconda3/envs/mindeye/lib/python3.10/site-packages/accelerate/data_loader.py", line 630, in __iter__
    self.set_epoch(self.iteration)
  File "/root/miniconda3/envs/mindeye/lib/python3.10/site-packages/accelerate/data_loader.py", line 707, in set_epoch
    if hasattr(self.batch_sampler.sampler, "set_epoch"):
AttributeError: 'NoneType' object has no attribute 'sampler'

So, I changed "utilis.py"
train_dl = torch.utils.data.DataLoader(train_data, batch_size=32, num_workers=1, shuffle=False), set batch_size to 32
but I still can not run the training process
![image](https://github.com/MedARC-AI/fMRI-reconstruction-NSD/assets/64114155/0f80d954-3f17-4847-a400-3fec13727e67)

**Comment by DavisMeee** [comment]
Hey, you can see my solution in #34 And I think this may help you to solve this

**Comment by Rui00000** [comment]
Hey,have you resolved this problem?
