### ISSUE TITLE
ValueError: didn't find ['jpg', 'png'] in ['__key__', '__url__', 'coco73k.npy']

### ISSUE THREAD

**Issue by minghu0830** [MedARC-AI/fMRI-reconstruction-NSD#45]
Could you please tell me what caused the following error log?

**my bash:**
CUDA_VISIBLE_DEVICES=0 python Reconstructions.py \
                        --model_name prior_257_final_subj01_bimixco_softclip_byol \
                        --autoencoder_name autoencoder_subj01_4x_locont_no_reconst \
                        --data_path ./data \
                        --subj 1 \
                        --img2img_strength 0 \
                        --recons_per_sample 16 \
                        --vd_cache_dir ./ckpt_d

**log：**
device: cuda
subj 1 num_voxels 15724
Traceback (most recent call last):
  File "/mnt/sda/huming/fmri2img/fMRI-reconstruction-NSD/src/Reconstructions.py", line 147, in <module>
    for val_i, (voxel, img_input, coco) in enumerate(val_dl):
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/webdataset/pipeline.py", line 70, in iterator
    yield from self.iterator1()
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/webdataset/filters.py", line 487, in _batched
    for sample in data:
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/webdataset/filters.py", line 397, in _to_tuple
    for sample in data:
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/webdataset/filters.py", line 343, in _rename
    if handler(exn):
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/webdataset/filters.py", line 86, in reraise_exception
    raise exn
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/webdataset/filters.py", line 336, in _rename
    {
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/webdataset/filters.py", line 337, in <dictcomp>
    k: getfirst(sample, v, missing_is_error=True)
  File "/home/huming/anaconda3/envs/mindeye/lib/python3.10/site-packages/webdataset/filters.py", line 123, in getfirst
    raise ValueError(f"didn't find {keys} in {list(a.keys())}")
ValueError: didn't find ['jpg', 'png'] in ['__key__', '__url__', 'coco73k.npy']

**Comment by Zhuxl123** [comment]
same question, how to deal with it?
